/*
 * Projet Programmation - EPF LIFE
 * A.SYLARD / N.TROUILLET / M.PHELIP / M.GOMBAULT
 * Classe Jauge
 */
package epf.life;

import javax.swing.ImageIcon;

/**
 *
 * @author Utilisateur
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        
        ImageIcon FondCode = new javax.swing.ImageIcon(getClass().getResource("/images/FondCode.jpg"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JaugeEducation = new javax.swing.JLabel();
        JaugeSociabilite = new javax.swing.JLabel();
        JaugeSante = new javax.swing.JLabel();
        Jauges = new javax.swing.JLabel();
        Personnage = new javax.swing.JLabel();
        Evenement = new javax.swing.JPanel();
        NomEvent = new javax.swing.JLabel();
        DescriptionEvent = new javax.swing.JLabel();
        DescriptionChoix1 = new javax.swing.JLabel();
        DescriptionChoix2 = new javax.swing.JLabel();
        DescriptionChoix3 = new javax.swing.JLabel();
        DescriptionChoix4 = new javax.swing.JLabel();
        Choix1 = new javax.swing.JButton();
        Choix2 = new javax.swing.JButton();
        Choix3 = new javax.swing.JButton();
        Choix4 = new javax.swing.JButton();
        ImageDeFond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JaugeEducation.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JaugeEducation.setText("100/100");
        getContentPane().add(JaugeEducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, 50));

        JaugeSociabilite.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JaugeSociabilite.setText("100/100");
        getContentPane().add(JaugeSociabilite, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 140, 50));

        JaugeSante.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JaugeSante.setText("100/100");
        getContentPane().add(JaugeSante, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, 150, 50));

        Jauges.setBackground(new java.awt.Color(255, 255, 255));
        Jauges.setForeground(new java.awt.Color(255, 255, 255));
        Jauges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jauge.jpg"))); // NOI18N
        Jauges.setText("jLabel2");
        Jauges.setPreferredSize(new java.awt.Dimension(1390, 192));
        getContentPane().add(Jauges, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1390, 192));

        Personnage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jousset.jpg"))); // NOI18N
        Personnage.setText("jLabel1");
        getContentPane().add(Personnage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 250, 500, 700));

        Evenement.setBackground(new java.awt.Color(255, 255, 255));

        NomEvent.setBackground(new java.awt.Color(0, 0, 0));
        NomEvent.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        NomEvent.setText("Titre Event");

        DescriptionEvent.setBackground(new java.awt.Color(0, 0, 0));
        DescriptionEvent.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        DescriptionEvent.setText("Description Event");

        DescriptionChoix1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        DescriptionChoix1.setText("DescriptionChoix1");

        DescriptionChoix2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        DescriptionChoix2.setText("DescriptionChoix2");

        DescriptionChoix3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        DescriptionChoix3.setText("DescriptionChoix3");

        DescriptionChoix4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        DescriptionChoix4.setText("DescriptionChoix4");

        Choix1.setText("Choix1");
        Choix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choix1ActionPerformed(evt);
            }
        });

        Choix2.setText("Choix2");
        Choix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choix2ActionPerformed(evt);
            }
        });

        Choix3.setText("Choix3");
        Choix3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choix3ActionPerformed(evt);
            }
        });

        Choix4.setText("Choix4");
        Choix4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choix4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EvenementLayout = new javax.swing.GroupLayout(Evenement);
        Evenement.setLayout(EvenementLayout);
        EvenementLayout.setHorizontalGroup(
            EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(300, Short.MAX_VALUE)
                    .addComponent(NomEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(272, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(39, Short.MAX_VALUE)
                    .addComponent(DescriptionEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(38, Short.MAX_VALUE)
                    .addComponent(Choix1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(660, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(39, Short.MAX_VALUE)
                    .addComponent(Choix2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(659, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EvenementLayout.createSequentialGroup()
                    .addGap(626, 626, 626)
                    .addComponent(Choix3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(627, Short.MAX_VALUE)
                    .addComponent(Choix4, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(73, Short.MAX_VALUE)
                    .addComponent(DescriptionChoix1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(692, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EvenementLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(DescriptionChoix2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(696, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EvenementLayout.createSequentialGroup()
                    .addGap(663, 663, 663)
                    .addComponent(DescriptionChoix3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EvenementLayout.createSequentialGroup()
                    .addGap(665, 665, 665)
                    .addComponent(DescriptionChoix4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        EvenementLayout.setVerticalGroup(
            EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EvenementLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NomEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(471, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EvenementLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(DescriptionEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(286, Short.MAX_VALUE)
                    .addComponent(Choix1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(426, Short.MAX_VALUE)
                    .addComponent(Choix2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(286, Short.MAX_VALUE)
                    .addComponent(Choix3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(151, 151, 151)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(426, Short.MAX_VALUE)
                    .addComponent(Choix4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(DescriptionChoix1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(174, Short.MAX_VALUE)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(449, Short.MAX_VALUE)
                    .addComponent(DescriptionChoix2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(310, Short.MAX_VALUE)
                    .addComponent(DescriptionChoix3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(175, 175, 175)))
            .addGroup(EvenementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvenementLayout.createSequentialGroup()
                    .addContainerGap(449, Short.MAX_VALUE)
                    .addComponent(DescriptionChoix4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );

        getContentPane().add(Evenement, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 1190, 560));

        ImageDeFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campus.jpg"))); // NOI18N
        getContentPane().add(ImageDeFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Choix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choix1ActionPerformed

    private void Choix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choix2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choix2ActionPerformed

    private void Choix3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choix3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choix3ActionPerformed

    private void Choix4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choix4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choix4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choix1;
    private javax.swing.JButton Choix2;
    private javax.swing.JButton Choix3;
    private javax.swing.JButton Choix4;
    private javax.swing.JLabel DescriptionChoix1;
    private javax.swing.JLabel DescriptionChoix2;
    private javax.swing.JLabel DescriptionChoix3;
    private javax.swing.JLabel DescriptionChoix4;
    private javax.swing.JLabel DescriptionEvent;
    private javax.swing.JPanel Evenement;
    private javax.swing.JLabel ImageDeFond;
    private javax.swing.JLabel JaugeEducation;
    private javax.swing.JLabel JaugeSante;
    private javax.swing.JLabel JaugeSociabilite;
    private javax.swing.JLabel Jauges;
    private javax.swing.JLabel NomEvent;
    private javax.swing.JLabel Personnage;
    // End of variables declaration//GEN-END:variables
}
